version: '3'

services:

  configs1:
    container_name: configs1
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 10001:27017
    volumes:
      - configs1:/data/db

  configs2:
    container_name: configs2
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 10002:27017
    volumes:
      - configs2:/data/db

  configs3:
    container_name: configs3
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 10003:27017
    volumes:
      - configs3:/data/db

  shard11:
    container_name: shard11
    image: mongo
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db
    ports:
      - 20001:27017
    volumes:
      - shard11:/data/db

  shard12:
    container_name: shard12
    image: mongo
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db
    ports:
      - 20002:27017
    volumes:
      - shard12:/data/db

  shard13:
    container_name: shard13
    image: mongo
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db
    ports:
      - 20003:27017
    volumes:
      - shard13:/data/db
  shard21:
    container_name: shard21
    image: mongo
    command: mongod --shardsvr --replSet shard2 --port 27017 --dbpath /data/db
    ports:
      - 20004:27017
    volumes:
      - shard21:/data/db

  shard22:
    container_name: shard22
    image: mongo
    command: mongod --shardsvr --replSet shard2 --port 27017 --dbpath /data/db
    ports:
      - 20005:27017
    volumes:
      - shard22:/data/db

  shard23:
    container_name: shard23
    image: mongo
    command: mongod --shardsvr --replSet shard2 --port 27017 --dbpath /data/db
    ports:
      - 20006:27017
    volumes:
      - shard23:/data/db

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/configs1:27017,configs2:27017,configs3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 30000:27017


volumes:
  configs1: {}
  configs2: {}
  configs3: {}
  shard11: {}
  shard12: {}
  shard13: {}
  shard21: {}
  shard22: {}
  shard23: {}